# The finite volume method for diffusion problems
The governing equation of steady state diffusion of a transport property $\phi$ is given as 
$$
\nabla \cdot (\Gamma \ \nabla \phi) + S_{\phi} = 0
$$

The control volume integration, which forms the key step of the finite volume method that distinguishes it from all other CFD techniques, yields the following form: 
$$
\int_{CV} \nabla \cdot (\Gamma \ \nabla \phi) dV + \int_{CV} S_{\phi} dV 
    = \int_A \mathbf{n} \cdot (\Gamma \ \nabla \phi) dA + \int_{CV} S_{\phi} dv = 0
$$

## One dimensional steady state diffusion

Consider the steady state diffusion of a property $\phi$ in a one-dimension domain. The process is governed by 

$$
\frac{d}{dx}(\Gamma \frac{d \phi}{dx}) + S = 0
$$

Where $\Gamma$ is the diffusion coefficient and S is the source term. Boundary values of $\phi$ are given as A and B.


  
A ----o----o----o ... o----o---- B

### One dimensional steady state conductive heat transfer

$$
\frac{d}{dx}(\kappa \frac{d T}{dx}) + S = 0
$$

where thermal conductivity $\kappa$ takes the place of $\Gamma$ in the generic equation and the dependent vairable is temperature $T$.


#### Example 1
Consider the problem of source-free heat conduction in an insulated rod
whose ends are maintained at constant temperatures of 100°C and 500°C
respectively. The length of the rod is 0.5 m.

$$
\frac{d}{dx}(\kappa \frac{d T}{dx}) + S = 0
$$

Calculate the steady state temperature distribution in the rod. Thermal conductivity $\kappa$ equals 1000 W/m.K, cross-sectional area $A$ is $10 × 10^{-3}$ m

In [1]:
import numpy as np

# Solution to Example 1

L = 0.5
n = 5 # number of control volumes
dx = L/n
k = 1000 # thermal conductivity
A = 10e-3 # Area

# Boundary conditions
T_A = 100
T_B = 500

mat = np.zeros((n, n))
b = np.zeros((n,))

# Interior nodal points
for i in range(1, n - 1):
    aw = k * A / dx
    ae = k * A / dx
    ap = aw + ae
    mat[i, i] = ap
    mat[i, i-1] = - aw
    mat[i, i + 1] = -ae
    

# First Node
aw = 0
ae = k * A / dx
sp = - 2 * k * A / dx
su = 2 * k * A * T_A/ dx
ap = aw + ae -sp
mat[0, 0] = ap
mat[0, 1] = -ae

# Last Node
aw = k * A / dx
ae = 0
sp = - 2 * k * A / dx
su = 2 * k * A * T_B/ dx
ap = aw + ae - sp
mat[n-1, n-1] = ap
mat[n-1, n-2] = -aw

# 
b[0] = 200 * T_A
b[n-1] = 200 * T_B

In [2]:

np.linalg.solve(mat, b)

array([140., 220., 300., 380., 460.])

In [ ]:
import numpy as np

L = 0.5
n = 5  # number of control volumes
dx = L / n
k = 1000  # thermal conductivity
A = 10e-3  # Area

# Boundary conditions
T_A = 100
T_B = 500

# Create diagonal, lower, and upper diagonals
aw = np.full(n - 1, k * A / dx)
ae = np.full(n - 1, k * A / dx)
ap = np.full(n, 0.0)

# Boundary node values
ap[0] = k * A / dx
ap[n - 1] = k * A / dx

# Create the main diagonal
ap[1:n - 1] = aw + ae

# Create the coefficient matrix
mat = np.diag(ap) + np.diag(-aw, -1) + np.diag(-ae, 1)

# Create the right-hand side vector
b = np.zeros(n)
b[0] = 2 * k * A * T_A / dx
b[n - 1] = 2 * k * A * T_B / dx


In [3]:
# TODO: 1D with constant source
# TODO: 1D with linear source
# TODO: Simple 2D and 3D

import numpy as np
field = np.arange(9).reshape(3,3)
field

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
def foward_diff_x(f, dx):
    diff = np.zeros_like(f)

    diff[:, :-1] = (f[:, 1:] - f[:, :-1] )/dx
    return diff
    

In [8]:
foward_diff_x(field, 1)

array([[1, 1, 0],
       [1, 1, 0],
       [1, 1, 0]])

In [6]:
field[1:, :]

array([[3, 4, 5],
       [6, 7, 8]])